services:
  app:
    build: .
    restart: unless-stopped
    depends_on:
      - database
    networks:
      - app-network
    ports:
      - "80:80"
      - "443:443"
  database:
    image: mongo:8.0
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASS}
      MONGO_INITDB_DATABASE: ${DB_NAME}
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network
    ports:
      - 27017:27017

volumes:
  mongodb_data:

networks:
  app-network:
    driver: bridge
